DEVICES:
  SUT:
    ID: 1  
    TYPE: SUT
    CONN_TYPE: SSH
    CONN_PORT: 22
    IP: 192.168.226.128
    USER: falish
    PASS: pass

  BIOS-SER:
    ID: 2
    TYPE: SERIAL
    CONN_TYPE: COM
    CONN_PORT: 100

